// src/lib/components/portfolio/PortfolioGrid.svelte
<script lang="ts">
  import type { PortfolioItem } from '#lib/types.ts';
  import PortfolioCard from './PortfolioCard.svelte';
  import PortfolioModal from './PortfolioModal.svelte';

  let { items }: { items: PortfolioItem[] } = $props();

  let activeItem = $state.raw<PortfolioItem | null>(null);

  let sorted = $derived(
    [...items].sort((a, b) => a.display_order - b.display_order),
  );
</script>

{#if items.length === 0}
  <div class="mp-card text-center">
    <p class="mp-body">No portfolio items available yet.</p>
  </div>
{:else}
  <section aria-label="Projects" class="mp-grid">
    {#each sorted as item (item.id)}<PortfolioCard
        {item}
        onOpen={(selectedItem) => (activeItem = selectedItem)}
      />{/each}
  </section>
{/if}
{#if activeItem}<PortfolioModal
    item={activeItem}
    onClose={() => (activeItem = null)}
  />{/if}

// app/components/portfolio/portfolio-grid.tsx
import { useState } from "react";
import type { PortfolioItem } from "~/types";
import { cn } from "~/lib/utils";
import { PortfolioCard } from "./portfolio-card";
import { PortfolioModal } from "./portfolio-modal";

interface PortfolioGridProps {
  items: PortfolioItem[];
  className?: string;
}

export function PortfolioGrid({ items, className }: PortfolioGridProps) {
  const [activeItem, setActiveItem] = useState<PortfolioItem | null>(null);

  if (items.length === 0) {
    return (
      <div className={cn("mp-card text-center", className)}>
        <p className="mp-body">
          No portfolio items available yet.
        </p>
      </div>
    );
  }

  const sorted = [...items].sort((a, b) => {
    return a.display_order - b.display_order;
  });

  return (
    <>
      <section
        aria-label="Projects"
        className={cn(
          "mp-grid",
          className
        )}
      >
        {sorted.map((item) => (
          <PortfolioCard
            key={item.id}
            item={item}
            onOpen={(selectedItem) => setActiveItem(selectedItem)}
          />
        ))}
      </section>

      {activeItem && (
        <PortfolioModal item={activeItem} onClose={() => setActiveItem(null)} />
      )}
    </>
  );
}
