// app/components/effects/portrait-reveal.tsx
import { useRef, useState } from "react";
import type { PointerEvent } from "react";
import { PortraitDither } from "./portrait-dither";
import { useMotionPreferences } from "./motion-provider";

/** Reveal the accessible photo through a dithered print that is present before hydration. */
export function PortraitReveal({ src, alt }: { readonly src: string; readonly alt: string }) {
  const ref = useRef<HTMLDivElement>(null);
  const { motionAllowed, finePointer } = useMotionPreferences();
  const [inside, setInside] = useState(false);
  function move(event: PointerEvent<HTMLDivElement>) {
    if (!motionAllowed || !finePointer || event.pointerType === "touch") return;
    const element = ref.current;
    if (!element) return;
    const rect = element.getBoundingClientRect();
    element.style.setProperty("--reveal-x", `${event.clientX - rect.left}px`);
    element.style.setProperty("--reveal-y", `${event.clientY - rect.top}px`);
    setInside(true);
  }
  return (
    <div ref={ref} className="portrait-reveal" data-reveal={inside && motionAllowed && finePointer} onPointerMove={move} onPointerLeave={() => setInside(false)}>
      <img src={src} alt={alt} fetchPriority="high" className="h-full w-full object-cover" />
      <PortraitDither src={src} />
      {motionAllowed && finePointer && <span className="portrait-hint">Move to reveal</span>}
    </div>
  );
}

// src/lib/components/effects/PortraitReveal.svelte
<script lang="ts">
  import PortraitDither from './PortraitDither.svelte';
  import { getMotion } from './motion.svelte.ts';

  let { src, alt }: { src: string; alt: string } = $props();

  let inside = $state(false);

  const motion = getMotion();

  function move(event: PointerEvent & { currentTarget: HTMLDivElement }) {
    if (
      !motion.motionAllowed ||
      !motion.finePointer ||
      event.pointerType === 'touch'
    )
      return;
    const rect = event.currentTarget.getBoundingClientRect();
    event.currentTarget.style.setProperty(
      '--reveal-x',
      `${event.clientX - rect.left}px`,
    );
    event.currentTarget.style.setProperty(
      '--reveal-y',
      `${event.clientY - rect.top}px`,
    );
    inside = true;
  }
</script>

<div
  class="portrait-reveal"
  role="presentation"
  data-reveal={inside && motion.motionAllowed && motion.finePointer}
  onpointermove={move}
  onpointerleave={() => (inside = false)}
>
  <img {src} {alt} fetchpriority="high" class="h-full w-full object-cover" />
  <PortraitDither {src} />
  {#if motion.motionAllowed && motion.finePointer}<span class="portrait-hint"
      >Move to reveal</span
    >{/if}
</div>
